package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.SequenceDO;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jan 28 12:13:55 GMT+08:00 2021
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Jan 28 12:13:55 GMT+08:00 2021
     */
    int insertSelective(SequenceDO record);
    SequenceDO getSequenceByName(String name);
    int  updateByPrimaryKeySelective(SequenceDO sequenceDO);
}